# Docs: https://goreleaser.com
# from https://github.com/pgrok/pgrok/blob/main/.goreleaser.pgrokd.yml
#
# usage:
#  goreleaser build --snapshot --clean -f .github/goreleaser.yml
#
dist: build/dist
before:
  hooks:
    - go mod tidy
project_name: kite
builds:
  - main: ./cmd/kite
    binary: kite
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - upx -6 "{{ .Path }}"
archives:
  - format: tar.gz
    wrap_in_directory: false
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'
snapshot:
  name_template: "SNAPSHOT-{{.ShortCommit}}"
changelog:
  skip: true