name: chlog
desc: quick generate change log by git
link: https://github.com/gookit/gitw # project link
deps: go
workdir: # on run command
install: go install github.com/gookit/gitw/cmd/chlog@latest
update: '@install'
remove: rm -f $GOPATH/bin/chlog
afterTips:
  install: tool has been installed to the $GOPATH/bin
