/**
 * auto generated by https://github.com/gookit/Kite
 *
 * @author https://github.com/inhere
 */
package api

import (
	"github.com/gookit/rux"
)

{{range $i, $m := .Actions }}
// {{ $m.MethodName }} {{ $m.MethodDesc }}
func (*{{ $.GroupName}}) {{ $m.MethodName }}(c *rux.Context) {
	c.Text(200, "hello")
}
{{end}}


