
# will set local_proxy before run matched command
proxy_cmd:
  command_ids:
    - 'github:tag:delete'
  group_limits:
    github: [acp, push, update]

# local proxy hosts
local_proxy:
  # export http_proxy=http://127.0.0.1:1081;export https_proxy=http://127.0.0.1:1081;
  http_proxy: ${PROXY_SERVE}
  https_proxy: ${PROXY_SERVE}

logger:
  logfile: $tmp/logs/kite-go.log
  buffer_size: 8192
  use_json: false
  level: debug
  level_mode: 1
  backup_num: 10

srv_logger:
  logfile: $tmp/logs/kite-serve.log
  buffer_size: 8192
  use_json: false
  level: debug
  level_mode: 1

# locales language
language:
  lang_dir: $data/language
  def_lang: zh-CN
  lang_map:
    en: English
    zh-CN: 简体中文
