proxy_cmd:
  # export http_proxy=http://127.0.0.1:1081;export https_proxy=http://127.0.0.1:1081;
  env:
    http_proxy: ${PROXY_SERVE}
    https_proxy: ${PROXY_SERVE}
  command_ids:
    - 'github:tag:delete'
  group_limits:
    github: [acp, push, update]

logger:
  logfile: $tmp/logs/kite-go.log
  buffer_size: 8192
  use_json: false
  level: debug
  level_mode: 1

language:
  lang_dir: $data/language
  def_lang: zh-CN
  lang_map:
    en: English
    zh-CN: 简体中文
