# common config file for kite

#
# global vars definitions. see kiteext.NewVarMap
# built in: os, user, env, bin_name
# access: ${gvs.user}, ${gvs.some}
global_vars:
  some: value

# user custom path aliases map. see kiteext.PathMap
# 使用：在配置和script中使用, 格式：${paths.key}
# format: `name: realpath`
#
# access: $paths.home
path_map:
  gobin: ${GOPATH}/bin
  wp: ${HOME}/Workspace

# will set local_proxy before run matched command
proxy_cmd:
  command_ids:
    - 'github:tag:delete'
  group_limits:
    github: [acp, push, update]

# local proxy hosts
local_proxy:
  # export http_proxy=http://127.0.0.1:1081;export https_proxy=http://127.0.0.1:1081;
  http_proxy: ${PROXY_SERVE}
  https_proxy: ${PROXY_SERVE}

logger:
  logfile: $tmp/logs/kite-go.log
  buffer_size: 8192
  use_json: false
  level: debug
  level_mode: 1
  backup_num: 10

srv_logger:
  logfile: $tmp/logs/kite-serve.log
  buffer_size: 8192
  use_json: false
  level: debug
  level_mode: 1

# locales language
language:
  lang_dir: $data/language
  def_lang: zh-CN
  lang_map:
    en: English
    zh-CN: 简体中文
