
# plugins for kite
plugin:
  # deny plugin names
  deny_names: []
  config_file: $config/modules/plugins.yml
  # plugin bin search dirs
  plugin_dirs:
    - plugins # relative base dir.
    - ${GOPATH}/bin

# scripts for kite
script:
  script_dirs:
    - scripts # relative base dir.
  define_files:
    - $config/modules/scripts.yml

# quick package manage
package:
  version: 1
  workdir: ''
  timeout: 10m
  metadir: $config/pkgm

jenkins:
  host_url: xyz
  api_token:

quick_jump:
  data_dir: $data
  aliases:
    home: ~
