
pluginManager:
  enable: true
  plugins_dir:
    - plugins # relative base dir.
    - ${GOPATH}/bin
  data_config: $config/modules/plugins.yml

packageManager:
  version: 1
  workdir: ''
  timeout: 10m
  metadir: $config/pkgm

scriptManager:
  enable: true
  scripts_dir:
    - scripts # relative base dir.
  data_config: $config/modules/scripts.yml

jenkins:
  host_url: xyz
  api_token:
