
# plugins for kite
plugin:
  # deny plugin names
  deny_names: []
  config_file: $config/module/plugins.yml
  # plugin bin search dirs
  plugin_dirs:
    - plugins # relative base dir.
    - ${GOPATH}/bin

# extension scripts in kite
script:
  # 独立的 script file 定义目录.
  script_dirs:
    - $base/scripts # relative base dir.
  # 独立的 script app 定义文件目录.
  script_app_dirs:
    - $base/script-app
  # 简单的 script task 定义文件配置
  define_files:
    - $config/module/scripts.yml
    - ?$config/module/scripts.$os.yml
  # 自动从当前目录或父级目录中寻找 script task 定义文件
#  auto_task_files: [ 'kite.tasks', 'kite.script', 'kite.scripts' ]
#  auto_task_exts: [ '.yml', '.yaml' ]

# use env in kite
use_env:
  enable: true
  config_file: $config/module/useenv.yml

# quick package manage
package:
  version: 1
  workdir: ''
  timeout: 10m
  metadir: $config/pkgm

jenkins:
  host_url: xyz
  api_token:

# quick jump manage
quick_jump:
  data_dir: $data
  check_exist: true
  named_paths:
    home: '~'

# https://cht.sh config
cheat:
  #  cache_dir: $tmp/cheat
  cache_dir: ~/.kite/tmp/cheat
