
# plugins for kite
plugin:
  # deny plugin names
  deny_names: []
  config_file: $config/module/plugins.yml
  # plugin bin search dirs
  plugin_dirs:
    - plugins # relative base dir.
    - ${GOPATH}/bin

# scripts in kite
script:
  # script file dir.
  script_dirs:
    - $base/scripts # relative base dir.
  define_dir: $config/scripts
  define_files:
    - $config/module/scripts.yml
    - ?$config/module/scripts.$os.yml
  type_shell:  # bash, sh, zsh or empty for run each command
  parse_env: true # parse ENV var in command line.
  scripts:
    test1: echo hello

# use env in kite
use_env:
  enable: true
  config_file: $config/module/useenv.yml

# quick package manage
package:
  version: 1
  workdir: ''
  timeout: 10m
  metadir: $config/pkgm

jenkins:
  host_url: xyz
  api_token:

# quick jump manage
quick_jump:
  data_dir: $data
  check_exist: true
  named_paths:
    home: '~'

# https://cht.sh config
cheat:
  #  cache_dir: $tmp/cheat
  cache_dir: ~/.kite/tmp/cheat
