
gitlab:
  main_remote: main
  fork_remote: origin
  git_url: git@gitlab.your.com
  host_url: http://gitlab.your.com/
  branch_aliases:
    h: head
    m: master
  # from /profile/personal_access_tokens
  token: '{$GITLAB_PA_TOKEN}'
  base_api: http://gitlab.your.com/api/v4

