/**
 * auto generated by https://github.com/gookit/ruxc
 *
 * @author https://github.com/inhere
 */
package api

import (
	"github.com/gookit/rux"
)

// {{ .GroupName }} {{ .GroupDesc }}
type {{ .GroupName }} struct {}

// AddRoutes register routes to the router
func (grp *Anything) AddRoutes(r *rux.Router) {
    {{range _, $m := .Methods }}
    	r.{{ $m.METHOD }}("{{ $m.Path }}", grp.{{ $m.MethodName }})
    {{end}}
}

{{range _, $m := .Methods }}
// {{ $m.MethodName }} {{ $m.MethodDesc }}
func (*{{ .GroupName}}) {{ $m.MethodName }}(c *rux.Context) {
	c.Text(200, "hello")
}
{{end}}
